server:
  port: 8080

spring:
  profiles:
    active: dev

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000   # 读超时时间
        loggerLevel: full # 日志级别

CAPITAL-STOCK-DATASOURCE-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

capital:
  stock-datasource:
    service-name: CAPITAL-STOCK-DATASOURCE-SERVICE
    retry: 3
    sleep-second: 1
